#!/home/cesar/Dev/flask/start_flask_afp/.venv/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from start_flask_afp.startproject import start_flask

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(start_flask())
